TARGET_CHROMOSOME = "zarkorist"
VALID_GENES = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
POPULATION_SIZE = 8
NUMBER_OF_ELITE_CHROMOSOMES = 1
TOURNAMENT_SELECTION_SIZE = 4
MUTATION_RATE = 0.25
